[Payment] fix cancel payment
Sylius/PayPalPlugin pull request #273
Opened 2023-01-27 09:36 UTC by oallain

| Q               | A
| --------------- | -----
| Branch?         | 1.5
| Bug fix?        | yes
| New feature?    | no
| Related tickets | replace #249

If the order already has a payment in the "new" status, then the Sylius orderPaymentProcessor must not be processed, otherwise a new payment in the "cart" status will be created, which will cause errors (2 payments in order ...).

Before : 
![image](https://user-images.githubusercontent.com/6593252/215053880-97319618-b24e-4a10-8281-15b71d494912.png)

After :
![image](https://user-images.githubusercontent.com/6593252/215054517-63061d73-37d3-4644-b16c-f57867a7e7d0.png)

2023-01-28 21:35 UTC, oallain commented
Hello @Zales0123 @SirDomin and others ;)

I fixed the bug that made two new payments (one in `new` and one in `cart`) when cancelling a payment. 
Because of this, the order was broken.

Regards

2023-05-05 09:01 UTC, Jibbarth approved these changes

2023-05-27 09:29 UTC, oallain commented
Hello,

This bug is still present, so I've rebased my branch to make it compatible with the new version.

Can you take a look? Ping @GSadee

2023-09-09 14:32 UTC, Zales0123 approved these changes

2023-09-23 23:11 UTC, diimpp requested changes

2023-09-23 23:11 UTC, diimpp commented on src/Controller/CancelLastPayPalPaymentAction.php
> +        $lastPayment = $order->getLastPayment();
Please check for last payment's factory, before using it.

This clause needs to be at https://github.com/Sylius/PayPalPlugin/blob/1.5/src/Processor/OrderPaymentProcessor.php as existing design calls for it.

2024-01-18 11:08 UTC, NoResponseMate approved these changes

2024-01-18 14:43 UTC, GSadee approved these changes

2024-01-18 14:44 UTC, merged

2024-01-18 14:44 UTC, GSadee commented
Thank you, Olivier! :1st_place_medal: